
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpmsosselmriytkdxdrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwbXNvc3NlbG1yaXl0a2R4ZHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5Njk3NTcsImV4cCI6MjA1MTU0NTc1N30.uKT5gfTPb90d-21oopQK4RXbUPuhlDW1v0QbZ6orCK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Custom type-safe wrappers for our RPC functions that aren't in the generated types
interface DonationWithUser {
  id: string;
  amount: number;
  donation_type: string;
  created_at: string;
  payment_status: string;
  payment_processor: string | null;
  transaction_id: string | null;
  completed_at: string | null;
  user: {
    username: string | null;
    email: string | null;
  };
}

interface FeedbackWithUser {
  id: string;
  feedback_text: string;
  created_at: string;
  status: string;
  admin_response: string | null;
  user: {
    username: string | null;
    email: string | null;
  };
}

// Custom functions to access RPCs with proper typing
export const customRpcs = {
  getAllDonationsWithUsers: async () => {
    const { data, error } = await supabase.rpc('get_all_donations_with_users');
    return { data: data as DonationWithUser[] | null, error };
  },
  
  updateDonationStatus: async (
    donationId: string, 
    status: string, 
    completedAt: string | null = null
  ) => {
    return await supabase.rpc('update_donation_status', {
      donation_id_param: donationId,
      status_param: status,
      completed_at_param: completedAt
    });
  },
  
  getAllFeedbackWithUsers: async () => {
    const { data, error } = await supabase.rpc('get_all_feedback_with_users');
    return { data: data as FeedbackWithUser[] | null, error };
  },
  
  updateFeedbackResponse: async (
    feedbackId: string, 
    response: string, 
    status: string = 'resolved'
  ) => {
    return await supabase.rpc('update_feedback_response', {
      feedback_id_param: feedbackId,
      admin_response_param: response,
      status_param: status
    });
  }
};
