// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpmsosselmriytkdxdrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwbXNvc3NlbG1yaXl0a2R4ZHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5Njk3NTcsImV4cCI6MjA1MTU0NTc1N30.uKT5gfTPb90d-21oopQK4RXbUPuhlDW1v0QbZ6orCK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);