// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpmsosselmriytkdxdrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwbXNvc3NlbG1yaXl0a2R4ZHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5Njk3NTcsImV4cCI6MjA1MTU0NTc1N30.uKT5gfTPb90d-21oopQK4RXbUPuhlDW1v0QbZ6orCK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Custom type-safe wrappers for our RPC functions that aren't in the generated types
interface DonationWithUser {
  id: string;
  amount: number;
  donation_type: string;
  created_at: string;
  payment_status: string;
  payment_processor: string | null;
  transaction_id: string | null;
  completed_at: string | null;
  user: {
    username: string | null;
    email: string | null;
  };
}

interface FeedbackWithUser {
  id: string;
  feedback_text: string;
  created_at: string;
  status: string;
  admin_response: string | null;
  user: {
    username: string | null;
    email: string | null;
  };
}

// Custom functions to access RPCs with proper typing
export const customRpcs = {
  getAllDonationsWithUsers: async () => {
    const { data, error } = await supabase.rpc('get_all_donations_with_users');
    return { 
      data: data as unknown as DonationWithUser[] | null, 
      error 
    };
  },
  
  updateDonationStatus: async (
    donationId: string, 
    status: string, 
    completedAt: string | null = null
  ) => {
    return await supabase.rpc('update_donation_status', {
      donation_id_param: donationId,
      status_param: status,
      completed_at_param: completedAt
    });
  },
  
  getAllFeedbackWithUsers: async () => {
    const { data, error } = await supabase.rpc('get_all_feedback_with_users');
    return { 
      data: data as unknown as FeedbackWithUser[] | null, 
      error 
    };
  },
  
  updateFeedbackResponse: async (
    feedbackId: string, 
    response: string, 
    status: string = 'resolved'
  ) => {
    return await supabase.rpc('update_feedback_response', {
      feedback_id_param: feedbackId,
      admin_response_param: response,
      status_param: status
    });
  },
  
  trackMovieViewWithCountry: async (
    movieId: string,
    userId: string | null = null,
    userIp: string | null = null,
    browserInfo: string | null = null,
    deviceInfo: string | null = null
  ) => {
    // First get country data from the edge function
    let countryData = { country: 'Unknown' };
    if (userIp) {
      try {
        const { data } = await supabase.functions.invoke('get-country-data', {
          body: { ip: userIp }
        });
        
        if (data && data.country) {
          countryData = data;
          console.log(`Detected country: ${data.country} for IP: ${userIp}`);
        }
      } catch (error) {
        console.error("Error getting country data:", error);
      }
    }
    
    // Call the RPC function to track the view
    return await supabase.rpc('track_movie_view_with_country', {
      p_movie_id: movieId,
      p_user_id: userId,
      p_user_ip: userIp,
      p_browser_info: browserInfo,
      p_device_info: deviceInfo,
      p_country_code: countryData.country
    });
  },
  
  getViewsByCountry: async (startDate?: string, endDate?: string) => {
    return await supabase.rpc('get_views_by_country', {
      start_date: startDate,
      end_date: endDate
    });
  },
  
  getBrowserStats: async (startDate: string, endDate: string) => {
    return await supabase.rpc('get_browser_stats', {
      start_date: startDate,
      end_date: endDate
    });
  },
  
  getDetailedDeviceStats: async (startDate: string, endDate: string) => {
    return await supabase.rpc('get_detailed_device_stats', {
      start_date: startDate,
      end_date: endDate
    });
  },
  
  getUserActivityStats: async (startDate: string, endDate: string) => {
    return await supabase.rpc('get_user_activity_stats', {
      start_date: startDate,
      end_date: endDate
    });
  }
};

export const getUserDeviceInfo = () => {
  const userAgent = navigator.userAgent;
  let device = "Unknown";

  if (/mobile/i.test(userAgent)) {
    device = "Mobile";
  } else if (/tablet/i.test(userAgent)) {
    device = "Tablet";
  } else {
    device = "Desktop";
  }

  return {
    device,
    browser: navigator.userAgent,
  };
};

export const fetchUserLocation = async () => {
  try {
    // ✅ First, Get the User's Public IP
    const ipResponse = await fetch("https://api64.ipify.org?format=json");
    const { ip } = await ipResponse.json();

    console.log("🛰️ User's IP:", ip);

    // ✅ Then, Use an IP Geolocation API
    const geoResponse = await fetch(`https://ipinfo.io/${ip}/json?token=88049e7d9b2938`);
    const locationData = await geoResponse.json();
    const browserData = getUserDeviceInfo();
    console.log("🌍 User's Location Data:", locationData);

    const analyticsData = {
      ip: ip,
      country: locationData.country,
      city: locationData.city,
      region: locationData.region,
      coordinates: locationData.loc, // "lat,long"
      device: browserData.device,
      browser: browserData.browser,
      timestamp: new Date().toISOString(),
    };

    // Write the data to the user_analytics table
    const { error } = await supabase.from('user_interactions').insert({analyticsData});

    if (error) {
      console.error("⚠️ Error writing user analytics data:", error);
    }

    return analyticsData;
  } catch (error) {
    console.error("⚠️ Error fetching user location:", error);
    return null;
  }
};
